sudo: required
services:
  - docker

before_install:
  - docker build -t kumarvdocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kumarvdocker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-east-2-510629544408
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY